### ISSUE TITLE
`<!--hidden-->` removes pages from the build process entirely

### ISSUE THREAD

**Issue by stephenlf** [ankitrgadiya/mdbook-hide#2]
**Expected behavior:**
Marking a chapter `<!--hidden-->` allows the chapter to be built into HTML while removing its entry from the Nav Bar produced by SUMMARY.md.

**Actual behavior:**
Marking a chapter `<!--hidden-->` removes it from the build process entirely. The chapter is not converted into HTML.

**Notes:**
This may be expected behavior. However, since this is functionally equivalent to just removing the chapter's entry from SUMMARY.md, I had hoped for this crate to do a bit more.

Thank you!

**Comment by stephenlf** [comment]
Duplicate of #1

**Comment by ankitrgadiya** [comment]
Hey @stephenlf, yes this is the expected behaviour. My usecase for this crate is to have the same SUMMARY.md file but based on the configuration keep or remove the page from the final build.

I keep my notes in mdbook but some pages have some internal pages from my work which I don't want on the public website, so I have two builds one keeps them and other removes them.
